/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'akaiser' at '8/3/16 5:18 PM' with Gradle 2.14
 *
 * @author akaiser, @date 8/3/16 5:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
